version: "2"

services:
  registry:
    image: registry:2
    restart: always
    env_file:
      - .env
    ports:
      - "5051:5000"
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - registrydata:/data
      - ./auth-htpswd:/auth
    networks:
      - local

  ui:
    image: joxit/docker-registry-ui:latest
    ports:
      - ${UI_PORT}:80
    environment:
      - REGISTRY_TITLE=My Private Docker Registry
      - REGISTRY_URL=http://${REGISTRY_URL}:${NGINX_PORT}
      - SINGLE_REGISTRY=true
    env_file:
      - .env
    depends_on:
      - registry

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    env_file:
      - .env
    ports:
      - "${NGINX_PORT}:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - local


networks:
  local:
volumes:
  registrydata:
    driver: local
